### ISSUE TITLE
NotImplementedError: Operation not supported or unimplemented on this platform

### ISSUE THREAD

**Issue by KyleSanderson** [bkerler/Loaders#49]
$ ./edl reset
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
Traceback (most recent call last):
  File "C:\Users\Llamar\Downloads\edl\edl", line 391, in <module>
    base.run()
  File "C:\Users\Llamar\Downloads\edl\edl", line 299, in run
    conninfo = self.doconnect(loop)
  File "C:\Users\Llamar\Downloads\edl\edl", line 193, in doconnect
    self.cdc.connected = self.cdc.connect(portname=self.portname)
  File "C:\Users\Llamar\Downloads\edl\edlclient\Library\Connection\usblib.py", line 226, in connect
    self.configuration = self.device.get_active_configuration()
  File "C:\Users\Llamar\AppData\Local\Programs\Python\Python39\lib\site-packages\usb\core.py", line 921, in get_active_configuration
    return self._ctx.get_active_configuration(self)
  File "C:\Users\Llamar\AppData\Local\Programs\Python\Python39\lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\Llamar\AppData\Local\Programs\Python\Python39\lib\site-packages\usb\core.py", line 249, in get_active_configuration
    self.managed_open()
  File "C:\Users\Llamar\AppData\Local\Programs\Python\Python39\lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\Llamar\AppData\Local\Programs\Python\Python39\lib\site-packages\usb\core.py", line 131, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "C:\Users\Llamar\AppData\Local\Programs\Python\Python39\lib\site-packages\usb\backend\libusb1.py", line 804, in open_device
    return _DeviceHandle(dev)
  File "C:\Users\Llamar\AppData\Local\Programs\Python\Python39\lib\site-packages\usb\backend\libusb1.py", line 652, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "C:\Users\Llamar\AppData\Local\Programs\Python\Python39\lib\site-packages\usb\backend\libusb1.py", line 600, in _check
    raise NotImplementedError(_strerror(ret))
NotImplementedError: Operation not supported or unimplemented on this platform

**Comment by bkerler** [comment]
This is for loaders only, wrong repo.
