### ISSUE TITLE
SM6225, 001b80e1 loader

### ISSUE THREAD

**Issue by RenateUSB** [bkerler/Loaders#97]
Here is a loader for the SM6225, 001b80e1 (and others?).
It was patched from a manufacturer's loader that had severe limitations on what areas it could program.
Since it was patched it will only work on devices without Secure Boot enabled.
The original certs have been wiped to avoid confusion.
This works on Onyx GoColor7 and Go103 ereaders.
[sm6225.zip](https://github.com/user-attachments/files/16116282/sm6225.zip)

**Comment by Z9044234820** [comment]
How do you get loaders?

**Comment by RenateUSB** [comment]
This is the GitHub for bkerler's Python EDL client.
Apparently you're not using that.

The EDL client that you are using only works with a Windows WinUsb driver.
You probably still have the Qualcomm virtual serial port driver installed.
Check the instructions for whichever EDL client you wish to use.

**Comment by jdkruzr** [comment]
> This is the GitHub for bkerler's Python EDL client. Apparently you're not using that.
> 
> The EDL client that you are using only works with a Windows WinUsb driver. You probably still have the Qualcomm virtual serial port driver installed. Check the instructions for whichever EDL client you wish to use.

thanks. can you tell whether this is a Python EDL client problem or a loader problem?

```
jtd@Aurigae:~/edl$ ./edl --loader=../Downloads/sm6225.bin
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.62 (c) B.Kerler 2018-2024.
main - Using loader ../Downloads/sm6225.bin ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: sahara
Traceback (most recent call last):
  File "/home/jtd/edl/./edl", line 393, in <module>
    base.run()
  File "/home/jtd/edl/./edl", line 293, in run
    version = conninfo.get("data").version
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'req' has no attribute 'version'
```

**Comment by magmk5507** [comment]
Hello! I have an Orbic Q10 RC609L with a Qualcomm 680 4G SM6225 processor (for T-Mobile). I have tried all the recommended methods, but it is completely blocked from all sides. I can only access Chrome, but it is useless. I cannot access the settings, and the links are either grayed out or missing. The only option now is to use Firehose, which is specifically designed for this processor; Firehose from other manufacturers does not work with the Qualcomm SM6225 processor because the digital signature is invalid. I need the original Firehose. Please, I beg you to help me. 
According to the log: 
CPU id - snC3B6C30D
OEM_PK_HASH (96) - C9C82CD41B6CA5361BDC1D186779671A9089B9AA14219BFEF23BF9386D1E8E12F463A228D12B73C1E0ECE5BED6F519AF
HWID - 001B80E100190005
SBL SW Ver. - 00000000
Thanks in advance and I really hope you can help me out.
